server:
  port: 80

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
    hikari:
      connection-init-sql: select 1
      maximum-pool-size: 2

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.plateer.ec1
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
#  type-aliases-package: com.plateer.ec1.claim com.plateer.ec1.order com.plateer.ec1.promotion com.plateer.ec1.payment
logging:
  level:
    jdbc:
      sqlony : off
      sqltiming : info
      resultsettable : info
      audit: off
      resultset : off
      connection: off
    org:
      springframework:
        transaction:
          interceptor: trace

site:
  url: http//localhost

inicis:
  vacct:
    url: https://iniapi.inicis.com/api/v1/formpay
    mid: INIpayTest
    apikey: ItEQKi3rY7uvDS8l